variable "stage" {
  description = "Staging environment such as dev or prd"
}

variable "project" {
  description = "Project name"
}

variable "git_repository" {
  description = "git repo name"
}

variable "name" {
  description = "Name of Cost and usage report"
  validation {
    condition     = length(var.name) < 47
    error_message = "Resource name is too long."
  }
}
variable "tag_KST" {
  description = "Indicate the tag to be used in the resources"
  default     = "Not Set"
}

variable "additional_policy"{
  description = "(REQUIRED) Additional policy for grafana workspace"
}

variable "enable"{
  description = "Sets whether the module will be deployed or not"
  default = true
}

variable "provider_name" {
  description = "(Required) The name of the provider to create."
}

variable "saml_metadata_document" {
  description = "(Required) An XML document generated by an identity provider that supports SAML 2.0."
}

